# -*- coding: utf-8 -*-
"""Kargah_HomeWork.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17thWyUivpw9Klu6uSsIE1po1UEbLprqe

Q 1
"""

a = int(input("a: "))
b = int(input("b: "))

x = - b / 2 * a
print(x)

"""Q 2"""

x = int(input("x: "))
y = int(input("y: "))

if x % y == 0:
  print("x is divisible by y")
else:
  print("x is not divisible by y")

"""Q 3"""

import math

a = int(input("a: "))
b = int(input("b: "))
c = int(input("c: "))

if b ** 2 - 4 * a * c < 0:
  print("No real roots")

elif b ** 2 - 4 * a * c == 0:
  x = - b / 2 * a
  print(f"x = {x}")
else:
  x1 = (- b + math.sqrt(b ** 2 - 4 * a * c)) / 2 * a
  x2 = (- b - math.sqrt(b ** 2 - 4 * a * c)) / 2 * a
  print(f"x1 = {x1}")
  print(f"x2 = {x2}")

"""Q 4"""

n = int(input("n: "))
m = int(input("m: "))

count = 1

while count * n < m:
  print(count * n)
  count += 1

"""Q 5"""

s = input("s: ")

for item in s.upper():
  print(item)